version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install Yarn
          command: sudo npm i -g yarn@1.12.3
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Test
          command: yarn test
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Run Type Check
          command: yarn type-check
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
